/**
 * Cloud-init script generator for OpenClaw agents
 * Generates the user-data script for EC2 instance provisioning
 */

import { generateConfigPatchScript } from "./config-generator";

export interface CloudInitConfig {
  /** Anthropic API key */
  anthropicApiKey: string;
  /** Tailscale auth key */
  tailscaleAuthKey: string;
  /** Gateway authentication token */
  gatewayToken: string;
  /** Gateway port (default: 18789) */
  gatewayPort?: number;
  /** Browser control port (default: 18791) */
  browserPort?: number;
  /** Enable Docker sandbox (default: true) */
  enableSandbox?: boolean;
  /** AI model to use (default: anthropic/claude-sonnet-4) */
  model?: string;
  /** Node.js version to install (default: 22) */
  nodeVersion?: number;
  /** NVM version to install (default: 0.40.1) */
  nvmVersion?: string;
  /** OpenClaw version (default: latest) */
  openclawVersion?: string;
  /** Trusted proxies for gateway (default: ["127.0.0.1"]) */
  trustedProxies?: string[];
  /** Workspace files to inject (path -> content) */
  workspaceFiles?: Record<string, string>;
  /** Additional environment variables */
  envVars?: Record<string, string>;
  /** Custom shell commands to run after OpenClaw setup */
  postSetupCommands?: string[];
  /** Tailscale hostname (default: system hostname) */
  tailscaleHostname?: string;
  /** Skip Tailscale installation (default: false) */
  skipTailscale?: boolean;
  /** Create ubuntu user (for Hetzner which uses root) */
  createUbuntuUser?: boolean;
}

/**
 * Generates a cloud-init bash script for OpenClaw deployment
 */
export function generateCloudInit(config: CloudInitConfig): string {
  const gatewayPort = config.gatewayPort ?? 18789;
  const nodeVersion = config.nodeVersion ?? 22;
  const nvmVersion = config.nvmVersion ?? "0.40.1";
  const openclawVersion = config.openclawVersion ?? "latest";
  const trustedProxies = config.trustedProxies ?? ["127.0.0.1"];

  // Generate Python config patch script
  const configPatchScript = generateConfigPatchScript({
    gatewayPort,
    gatewayToken: config.gatewayToken,
    trustedProxies,
    enableControlUi: true,
  });

  // Generate workspace files injection script
  const workspaceFilesScript = generateWorkspaceFilesScript(config.workspaceFiles);

  // Generate additional env vars
  const additionalEnvVars = config.envVars
    ? Object.entries(config.envVars)
        .map(([key, value]) => `echo 'export ${key}="${value}"' >> /home/ubuntu/.bashrc`)
        .join("\n")
    : "";

  // Generate post-setup commands
  const postSetupScript = config.postSetupCommands
    ? config.postSetupCommands.join("\n")
    : "";

  // Create ubuntu user section (for Hetzner)
  const createUserSection = config.createUbuntuUser
    ? `
# Create ubuntu user (Hetzner uses root by default)
useradd -m -s /bin/bash -G docker ubuntu || true
`
    : "";

  // Tailscale installation section
  const tailscaleSection = config.skipTailscale
    ? ""
    : `
# Install and configure Tailscale
echo "Installing Tailscale..."
curl -fsSL https://tailscale.com/install.sh | sh
tailscale up --authkey="\${TAILSCALE_AUTH_KEY}" --ssh${config.tailscaleHostname ? ` --hostname=${config.tailscaleHostname}` : ""} || echo "WARNING: Tailscale setup failed. Run 'sudo tailscale up' manually."
`;

  // Tailscale serve section
  const tailscaleServeSection = config.skipTailscale
    ? ""
    : `
# Enable Tailscale HTTPS proxy (requires HTTPS to be enabled in Tailscale admin console)
echo "Enabling Tailscale HTTPS proxy..."
tailscale serve --bg ${gatewayPort} || echo "WARNING: tailscale serve failed. Enable HTTPS in your Tailscale admin console first."
`;

  return `#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive

# ============================================
# OpenClaw Agent Provisioning Script
# Generated by agent-army Pulumi component
# ============================================

# Configuration
ANTHROPIC_API_KEY="\${ANTHROPIC_API_KEY}"
TAILSCALE_AUTH_KEY="\${TAILSCALE_AUTH_KEY}"
GATEWAY_TOKEN="\${GATEWAY_TOKEN}"
GATEWAY_PORT="${gatewayPort}"
NODE_VERSION="${nodeVersion}"
NVM_VERSION="${nvmVersion}"
OPENCLAW_VERSION="${openclawVersion}"

echo "Starting OpenClaw agent provisioning..."

# System updates
echo "Updating system packages..."
apt-get update
apt-get upgrade -y

# Install Docker
echo "Installing Docker..."
curl -fsSL https://get.docker.com | sh
systemctl enable docker
systemctl start docker
${createUserSection}
usermod -aG docker ubuntu

# Install NVM and Node.js for ubuntu user
echo "Installing Node.js $NODE_VERSION via NVM..."
sudo -u ubuntu bash << 'UBUNTU_SCRIPT'
set -e
cd ~

# Install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${nvmVersion}/install.sh | bash

# Load NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Install Node.js
nvm install ${nodeVersion}
nvm use ${nodeVersion}
nvm alias default ${nodeVersion}

# Install OpenClaw
npm install -g openclaw@${openclawVersion}

# Add NVM to bashrc if not already there
if ! grep -q 'NVM_DIR' ~/.bashrc; then
  echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
  echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' >> ~/.bashrc
fi
UBUNTU_SCRIPT

# Set environment variables for ubuntu user
echo 'export ANTHROPIC_API_KEY="\${ANTHROPIC_API_KEY}"' >> /home/ubuntu/.bashrc
${additionalEnvVars}
${tailscaleSection}
# Enable systemd linger for ubuntu user (required for user services to run at boot)
loginctl enable-linger ubuntu

# Start user's systemd instance (required for user services during cloud-init)
systemctl start user@1000.service

# Run OpenClaw onboarding as ubuntu user (skip daemon install, do it separately)
echo "Running OpenClaw onboarding..."
sudo -H -u ubuntu ANTHROPIC_API_KEY="\${ANTHROPIC_API_KEY}" GATEWAY_PORT="$GATEWAY_PORT" bash -c '
export HOME=/home/ubuntu
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

openclaw onboard --non-interactive --accept-risk \\
  --mode local \\
  --auth-choice apiKey \\
  --gateway-port $GATEWAY_PORT \\
  --gateway-bind loopback \\
  --skip-daemon \\
  --skip-skills || echo "WARNING: OpenClaw onboarding failed. Run openclaw onboard manually."
'

# Install daemon service with XDG_RUNTIME_DIR set
echo "Installing OpenClaw daemon..."
sudo -H -u ubuntu XDG_RUNTIME_DIR=/run/user/1000 bash -c '
export HOME=/home/ubuntu
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

openclaw daemon install || echo "WARNING: Daemon install failed. Run openclaw daemon install manually."
'

# Configure gateway for Tailscale Serve
echo "Configuring OpenClaw gateway..."
sudo -H -u ubuntu GATEWAY_TOKEN="\${GATEWAY_TOKEN}" python3 << 'PYTHON_SCRIPT'
${configPatchScript}
PYTHON_SCRIPT
${workspaceFilesScript}
${tailscaleServeSection}
${postSetupScript}
echo "============================================"
echo "OpenClaw agent setup complete!"
echo "============================================"
`;
}

/**
 * Generates bash script to inject workspace files
 */
function generateWorkspaceFilesScript(
  workspaceFiles?: Record<string, string>
): string {
  if (!workspaceFiles || Object.keys(workspaceFiles).length === 0) {
    return "";
  }

  const lines = [
    "",
    "# Inject workspace files",
    'echo "Injecting workspace files..."',
    "mkdir -p /home/ubuntu/.openclaw/workspace",
  ];

  for (const [filePath, content] of Object.entries(workspaceFiles)) {
    // Escape content for heredoc
    const escapedContent = content.replace(/\\/g, "\\\\").replace(/\$/g, "\\$");
    const fullPath = `/home/ubuntu/.openclaw/workspace/${filePath}`;
    const dirPath = fullPath.substring(0, fullPath.lastIndexOf("/"));

    lines.push(`mkdir -p "${dirPath}"`);
    lines.push(`cat > "${fullPath}" << 'WORKSPACE_FILE_EOF'`);
    lines.push(escapedContent);
    lines.push("WORKSPACE_FILE_EOF");
  }

  lines.push('chown -R ubuntu:ubuntu /home/ubuntu/.openclaw/workspace');
  lines.push('echo "Workspace files injected successfully"');

  return lines.join("\n");
}

/**
 * Interpolates environment variables in the cloud-init script
 * Call this with actual values before passing to EC2 user data
 */
export function interpolateCloudInit(
  script: string,
  values: {
    anthropicApiKey: string;
    tailscaleAuthKey: string;
    gatewayToken: string;
  }
): string {
  return script
    .replace(/\${ANTHROPIC_API_KEY}/g, values.anthropicApiKey)
    .replace(/\${TAILSCALE_AUTH_KEY}/g, values.tailscaleAuthKey)
    .replace(/\${GATEWAY_TOKEN}/g, values.gatewayToken);
}
