/**
 * Static bash provisioner template.
 *
 * This is a self-contained bash script with one placeholder: __CONFIG_B64__
 * which gets replaced with a base64-encoded JSON config blob at build time.
 *
 * The bash reads the JSON via jq and executes provisioning phases mechanically.
 * All decision-making logic lives in provisioner-config.ts (TypeScript).
 */

export const PROVISIONER_TEMPLATE = `#!/bin/bash
set -eo pipefail
export DEBIAN_FRONTEND=noninteractive

# ============================================
# OpenClaw Agent Provisioner
# Generated by clawup Pulumi component
# ============================================

# ===== CONFIG =====
CONFIG_B64="__CONFIG_B64__"
CONFIG_JSON=$(echo "$CONFIG_B64" | base64 -d)

# ===== HELPERS =====
cfg()     { echo "$CONFIG_JSON" | jq -r "$1"; }
cfg_raw() { echo "$CONFIG_JSON" | jq    "$1"; }
cfg_len() { echo "$CONFIG_JSON" | jq    "$1 | length"; }

# Run a command as ubuntu user with NVM sourced.
# The command is passed as an env var to avoid shell expansion issues.
run_as_ubuntu() {
  sudo -H -u ubuntu env \\
    HOME=/home/ubuntu \\
    CONFIG_JSON="$CONFIG_JSON" \\
    RUN_CMD="$1" \\
    bash -c '
      [ -s "$HOME/.profile" ] && . "$HOME/.profile"
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      eval "$RUN_CMD"
    '
}

# Run a base64-encoded bash script
run_encoded_script() {
  local encoded="$1"
  local as_user="\${2:-root}"
  if [ "$as_user" = "ubuntu" ]; then
    sudo -H -u ubuntu env \\
      HOME=/home/ubuntu \\
      CONFIG_JSON="$CONFIG_JSON" \\
      ENCODED_SCRIPT="$encoded" \\
      bash -c '
        [ -s "$HOME/.profile" ] && . "$HOME/.profile"
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        echo "$ENCODED_SCRIPT" | base64 -d | bash
      '
  else
    echo "$encoded" | base64 -d | bash
  fi
}

# ===== PHASE: System Setup =====
phase_system() {
  echo "Updating system packages..."
  apt-get update
  apt-get upgrade -y
  apt-get install -y unzip build-essential sudo jq

  # Docker
  if [ "$(cfg '.skipDocker')" != "true" ]; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
  fi

  # User creation
  if [ "$(cfg '.createUbuntuUser')" = "true" ]; then
    if [ "$(cfg '.skipDockerGroup')" = "true" ]; then
      echo "Creating ubuntu user (local Docker — no docker group)..."
      useradd -m -s /bin/bash ubuntu || true
    else
      echo "Creating ubuntu user with docker group..."
      useradd -m -s /bin/bash -G docker ubuntu || true
    fi
  fi

  # Add ubuntu to docker group (if Docker installed and user exists)
  if [ "$(cfg '.skipDocker')" != "true" ] && [ "$(cfg '.createUbuntuUser')" != "true" ]; then
    usermod -aG docker ubuntu
  fi
}

# ===== PHASE: Tailscale =====
phase_tailscale() {
  local auth_key=$(cfg '.tailscale.authKey')
  local hostname=$(cfg '.tailscale.hostname')

  echo "Installing Tailscale..."
  curl -fsSL https://tailscale.com/install.sh | sh

  local ts_args="--authkey=$auth_key --ssh"
  [ -n "$hostname" ] && ts_args="$ts_args --hostname=$hostname"

  tailscale up $ts_args || echo "WARNING: Tailscale setup failed. Run 'sudo tailscale up' manually."
}

# ===== PHASE: Deps (root install) =====
phase_deps_root() {
  local count=$(cfg_len '.depsRoot')
  for i in $(seq 0 $((count - 1))); do
    local name=$(cfg ".depsRoot[$i].name")
    echo "Installing dep: $name..."
    run_encoded_script "$(cfg ".depsRoot[$i].script")" root
  done
}

# ===== PHASE: NVM + Node.js + OpenClaw =====
phase_nvm_node() {
  local node_version=$(cfg '.nodeVersion')
  local nvm_version=$(cfg '.nvmVersion')
  local openclaw_version=$(cfg '.openclawVersion')

  echo "Installing Node.js $node_version via NVM..."
  sudo -u ubuntu bash << UBUNTU_SCRIPT
set -e
cd ~

# Install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$nvm_version/install.sh | bash

# Load NVM
export NVM_DIR="\\$HOME/.nvm"
[ -s "\\$NVM_DIR/nvm.sh" ] && . "\\$NVM_DIR/nvm.sh"

# Install Node.js
nvm install $node_version
nvm use $node_version
nvm alias default $node_version

# Install OpenClaw
npm install -g openclaw@$openclaw_version

# Add NVM to bashrc if not already there
if ! grep -q 'NVM_DIR' ~/.bashrc; then
  echo 'export NVM_DIR="\\$HOME/.nvm"' >> ~/.bashrc
  echo '[ -s "\\$NVM_DIR/nvm.sh" ] && . "\\$NVM_DIR/nvm.sh"' >> ~/.bashrc
fi
UBUNTU_SCRIPT
}

# ===== PHASE: Coding Agent CLI =====
phase_coding_agent() {
  local install_script=$(cfg '.codingAgent.installScript')
  local config_script=$(cfg '.codingAgent.configureScript')

  if [ -n "$install_script" ] && [ "$install_script" != "null" ]; then
    echo "Installing coding agent CLI..."
    run_encoded_script "$install_script" root
  fi

  if [ -n "$config_script" ] && [ "$config_script" != "null" ]; then
    echo "Configuring coding agent model..."
    run_encoded_script "$config_script" root
  fi
}

# ===== PHASE: Environment Variables =====
phase_env_vars() {
  echo "Setting environment variables..."

  # Write all profile env vars
  echo "$CONFIG_JSON" | jq -r '.profileEnvVars | to_entries[] | "export \\(.key)=\\(.value | @sh)"' | while IFS= read -r line; do
    echo "$line" >> /home/ubuntu/.profile
  done

  # Git identity
  local git_name=$(cfg '.gitIdentity.name // empty')
  if [ -n "$git_name" ]; then
    local git_email=$(cfg '.gitIdentity.email')
    sudo -u ubuntu git config --global user.name "$git_name"
    sudo -u ubuntu git config --global user.email "$git_email"
    echo "Configured git identity: $git_name <$git_email>"
  fi
}

# ===== PHASE: Deps post-install (as ubuntu) =====
phase_deps_post() {
  local count=$(cfg_len '.depsPostInstall')
  for i in $(seq 0 $((count - 1))); do
    local name=$(cfg ".depsPostInstall[$i].name")
    echo "Post-install: $name..."
    run_encoded_script "$(cfg ".depsPostInstall[$i].script")" ubuntu
  done
}

# ===== PHASE: Systemd =====
phase_systemd() {
  echo "Enabling systemd linger for ubuntu user..."
  loginctl enable-linger ubuntu
  systemctl start user@1000.service
}

# ===== PHASE: Onboard =====
phase_onboard() {
  echo "Running openclaw onboard..."
  run_as_ubuntu "$(cfg '.onboard.command') || echo 'WARNING: onboard exited non-zero (gateway not yet running — expected)'"
  echo "Onboarding complete"
}

# ===== PHASE: Post-provision hooks =====
phase_hooks_post_provision() {
  local count=$(cfg_len '.postProvisionHooks')
  for i in $(seq 0 $((count - 1))); do
    local name=$(cfg ".postProvisionHooks[$i].name")
    echo "Running postProvision hook for $name..."
    run_encoded_script "$(cfg ".postProvisionHooks[$i].script")" ubuntu
    echo "postProvision hook for $name complete"
  done
}

# ===== PHASE: Workspace Files =====
phase_workspace() {
  local count=$(cfg_len '.workspaceFiles')
  [ "$count" -eq 0 ] && return

  echo "Injecting workspace files..."
  mkdir -p /home/ubuntu/.openclaw/workspace

  for i in $(seq 0 $((count - 1))); do
    local path=$(cfg ".workspaceFiles[$i].path")
    local full_path="/home/ubuntu/.openclaw/workspace/$path"
    local dir_path=$(dirname "$full_path")
    local content=$(cfg ".workspaceFiles[$i].gzipBase64")

    mkdir -p "$dir_path"
    echo "$content" | base64 -d | gunzip > "$full_path"
  done

  chown -R ubuntu:ubuntu /home/ubuntu/.openclaw
  echo "Workspace files injected successfully"
}

# ===== PHASE: Plugins =====
phase_plugins() {
  # Install plugins via openclaw plugins install
  local plugin_count=$(cfg_len '.installablePlugins')
  if [ "$plugin_count" -gt 0 ]; then
    echo "Installing plugins..."
    for i in $(seq 0 $((plugin_count - 1))); do
      local name=$(cfg ".installablePlugins[$i]")
      run_as_ubuntu "openclaw plugins install $name || echo 'WARNING: $name plugin install failed. Install manually with: openclaw plugins install $name'"
    done
    echo "Plugin installation complete"
  fi

  # Install clawhub skills
  local skill_count=$(cfg_len '.clawhubSkills')
  if [ "$skill_count" -gt 0 ]; then
    echo "Installing clawhub skills..."
    for i in $(seq 0 $((skill_count - 1))); do
      local slug=$(cfg ".clawhubSkills[$i]")
      run_as_ubuntu "clawhub install $slug || echo 'WARNING: clawhub skill $slug install failed.'"
    done
    echo "Clawhub skills installation complete"
  fi
}

# ===== PHASE: Config (openclaw config set commands) =====
phase_config() {
  echo "Configuring OpenClaw settings..."

  # Execute all config set commands in a single ubuntu bash session
  sudo -H -u ubuntu env \\
    HOME=/home/ubuntu \\
    CONFIG_JSON="$CONFIG_JSON" \\
    bash << 'PHASE_CONFIG'
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

    count=$(echo "$CONFIG_JSON" | jq '.configSetCommands | length')

    for i in $(seq 0 $((count - 1))); do
      type=$(echo "$CONFIG_JSON" | jq -r ".configSetCommands[$i].type // \\"config_set\\"")
      key=$(echo "$CONFIG_JSON" | jq -r ".configSetCommands[$i].key")
      value=$(echo "$CONFIG_JSON" | jq ".configSetCommands[$i].value")
      comment=$(echo "$CONFIG_JSON" | jq -r ".configSetCommands[$i].comment // empty")

      [ -n "$comment" ] && echo "  $comment"

      if [ "$type" = "models_set" ]; then
        model=$(echo "$CONFIG_JSON" | jq -r ".configSetCommands[$i].value")
        openclaw models set "$model"
      else
        openclaw config set "$key" "$value"
      fi
    done
PHASE_CONFIG

  echo "Configuration complete"
}

# ===== PHASE: Pre-start hooks =====
phase_hooks_pre_start() {
  local count=$(cfg_len '.preStartHooks')
  for i in $(seq 0 $((count - 1))); do
    local name=$(cfg ".preStartHooks[$i].name")
    echo "Running preStart hook for $name..."
    run_encoded_script "$(cfg ".preStartHooks[$i].script")" ubuntu
    echo "preStart hook for $name complete"
  done
}

# ===== PHASE: Tailscale Proxy =====
phase_tailscale_proxy() {
  local port=$(cfg '.gatewayPort')
  local enable_funnel=$(cfg '.tailscale.enableFunnel')

  if [ "$enable_funnel" = "true" ]; then
    echo "Enabling Tailscale Funnel for webhook endpoint..."
    if tailscale funnel --bg "$port"; then
      echo "Tailscale Funnel enabled — webhook endpoint is publicly accessible"
    else
      echo "WARNING: tailscale funnel failed — falling back to tailscale serve"
      tailscale serve --bg "$port" || echo "WARNING: tailscale serve also failed."
    fi
  else
    echo "Enabling Tailscale HTTPS proxy..."
    tailscale serve --bg "$port" || echo "WARNING: tailscale serve failed."
  fi
}

# ===== PHASE: Daemon =====
phase_daemon() {
  local foreground=$(cfg '.foregroundMode')
  local gateway_token=$(cfg '.gatewayToken')
  local post_setup_count=$(cfg_len '.postSetupCommands')

  if [ "$foreground" = "true" ]; then
    # Run openclaw doctor before starting daemon in foreground
    echo "Running openclaw doctor..."
    run_as_ubuntu "openclaw doctor --fix --non-interactive || echo 'WARNING: openclaw doctor failed'"

    # Post-setup commands
    for i in $(seq 0 $((post_setup_count - 1))); do
      eval "$(cfg ".postSetupCommands[$i]")"
    done

    echo "============================================"
    echo "OpenClaw agent setup complete!"
    echo "============================================"

    # Start OpenClaw gateway in foreground (keeps container alive)
    echo "Starting OpenClaw gateway in foreground..."
    su - ubuntu -c '
      export HOME=/home/ubuntu
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      openclaw gateway &
      GW_PID=$!

      # Wait for gateway to create the pending pairing request, then approve it
      sleep 3
      if openclaw devices approve --latest --token "'"$gateway_token"'" 2>/dev/null; then
        echo "Auto-approved gateway device pairing"
      else
        echo "WARNING: Device pairing approval failed (may already be paired)"
      fi

      wait $GW_PID
    '
  else
    # Install daemon service AFTER config patch so gateway token matches
    echo "Installing OpenClaw daemon..."
    sudo -H -u ubuntu XDG_RUNTIME_DIR=/run/user/1000 bash -c '
      export HOME=/home/ubuntu
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      openclaw daemon install || echo "WARNING: Daemon install failed."
    '

    # Run openclaw doctor
    echo "Running openclaw doctor..."
    run_as_ubuntu 'openclaw doctor --fix --non-interactive || echo "WARNING: openclaw doctor failed"'

    # Auto-approve pending device pairing
    sleep 2
    run_as_ubuntu "openclaw devices approve --latest --token '$gateway_token' 2>/dev/null && echo 'Auto-approved gateway device pairing' || echo 'WARNING: Device pairing approval failed (may already be paired)'"

    # Post-setup commands
    for i in $(seq 0 $((post_setup_count - 1))); do
      eval "$(cfg ".postSetupCommands[$i]")"
    done

    echo "============================================"
    echo "OpenClaw agent setup complete!"
    echo "============================================"
  fi
}

# ===== MAIN =====
echo "Starting OpenClaw agent provisioning..."

phase_system

[ "$(cfg '.tailscale.skip')" != "true" ] && phase_tailscale

phase_deps_root
phase_nvm_node
phase_coding_agent
phase_env_vars
phase_deps_post

[ "$(cfg '.foregroundMode')" != "true" ] && phase_systemd

phase_onboard
phase_hooks_post_provision
phase_workspace
phase_plugins
phase_config
phase_hooks_pre_start

[ "$(cfg '.tailscale.skip')" != "true" ] && phase_tailscale_proxy

phase_daemon
`;
